/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.publicaciones.datos;

/**
 * Local interface for PublicacionSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface PublicacionSLLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Obtiene todos los registros de un catálogo.
    * @param parametros Filtro de búsqueda.
    * @return Lista de registros.
    */
   public java.util.LinkedList getRegistros( com.rapidsist.comun.bd.Registro parametros ) ;

   /**
    * Obtiene las propiedades de un usuario asociado al portal, como son su perfil de publicación, su nivel de acceso y su nombre de usuario
    * @param parametros Filtro de búsqueda.
    * @return resultado Registro con el resultado dela busqueda.
    */
   public com.rapidsist.comun.bd.Registro getPropiedadesUsuarioPublicaciones( com.rapidsist.comun.bd.Registro parametros ) ;

   /**
    * Obtiene un registros de una publicación y verifica los permisos necesarios para poder presentarla
    * @param parametros Filtro de búsqueda.
    * @return resultado Registro con el resultado dela busqueda.
    */
   public com.rapidsist.comun.bd.Registro getPublicacion( com.rapidsist.comun.bd.Registro parametros ) ;

   /**
    * Obtiene las secciones y las publicaciones que puede ver el usuario
    * @param parametros Conjunto de datos que son necesarios: sCveGpoEmpresa, sCvePortal, sNomAplicacionWeb
    * @return sMenu Cadena con código html que la jsp puede interpretar con ayuda de una hoja de estilos y de javascript.
    */
   public java.lang.String getMenuPublicaciones( com.rapidsist.comun.bd.Registro parametros ) ;

   /**
    * Borra una objeto del JNDI
    * @param sCveGpoEmpresa Clave del grupo de empresas
    * @param sCvePortal Clave del portal
    * @param sCveUsuario Clave del usuario
    * @return bExito Valor lógico con Verdadero si el objeto fue borrado y Falso si el objeto no se pudo borrar
    */
   public boolean BorraObjetoJNDI( java.lang.String sCveGpoEmpresa,java.lang.String sCvePortal,java.lang.String sCveUsuario ) ;

   /**
    * Obtiene las publicaciones que puede ver un usuario
    * @param parametros Conjunto de datos que son necesarios: sCveGpoEmpresa, sCvePortal, sNomAplicacionWeb
    * @return lista Lista con las publicaciones de la sección deseada de javascript.
    * @throws RemoteException
    */
   public java.util.LinkedList getPublicaciones( com.rapidsist.comun.bd.Registro parametros ) ;

   /**
    * Obtiene la historia de la sección seleccionada
    * @param parametros Valores que permiten realizar la consulta
    * @return sRuta Cadena con la ruta de la sección
    */
   public java.lang.String getHistoriaSeccion( com.rapidsist.comun.bd.Registro parametros ) ;

}
