/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.publicaciones.datos;

/**
 * Home interface for PublicacionSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface PublicacionSLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PublicacionSL";
   public static final String JNDI_NAME="PublicacionSL";

   public com.rapidsist.publicaciones.datos.PublicacionSL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
