/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.publicaciones.datos;

/**
 * Local home interface for PublicacionSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface PublicacionSLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PublicacionSLLocal";
   public static final String JNDI_NAME="PublicacionSLLocal";

   public com.rapidsist.publicaciones.datos.PublicacionSLLocal create()
      throws javax.ejb.CreateException;

}
