/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.bitacora.datos;

/**
 * Local home interface for BitacoraSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface BitacoraSLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BitacoraSLLocal";
   public static final String JNDI_NAME="BitacoraSLLocal";

   public com.rapidsist.portal.bitacora.datos.BitacoraSLLocal create()
      throws javax.ejb.CreateException;

}
