/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.bitacora.datos;

/**
 * Remote interface for BitacoraSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface BitacoraSL
   extends javax.ejb.EJBObject
{
   /**
    * Registra la visita que hace un usuario a una funcion del sistema.
    * @param sCveGpoEmpresa Clave del grupo de empresas.
	* @param sCvePortal Clave del portal.
    * @param sCveFuncion Es la clave de la función solicitada al sistema.
	* @param sNomFuncion Nombre de la funcion.
	* @param sCveUsuario Clave del usuario.
	* @param sNomUsuario Nombre del usuario.
	* @param sUrlServidor Url del servidor.
	* @param sParametros Objeto.
	* @param sDireccionIpUsuario Dirección ip del usaurio.
    * @throws LogicaNegocioException Se generó un error al registrar la funcion.
    */
   public void registraVisitaFuncion( java.lang.String sCveGpoEmpresa, java.lang.String sCvePortal, java.lang.String sCveFuncion,java.lang.String sNomFuncion,java.lang.String sCveUsuario,java.lang.String sNomUsuario,java.lang.String sUrlServidor,java.lang.String sParametros,java.lang.String sDireccionIpUsuario )
      throws com.rapidsist.portal.catalogos.LogicaNegocioException, java.rmi.RemoteException;

   /**
    * Almacena en formato XML los movimientos realizados en los registros de las tablas relacionadas a una función.
    * @param sCveFuncion Es la clave de la función.
    * @param registro Objeto registro con los datos de los campos llave de cada tabla.
    * @return <code> True </code> Si la actualización tuvo éxito.
    * @throws LogicaNegocioException Se generó un error al registrar en la bitácora.
    */
   public java.lang.String registraBitacora( java.lang.String sCveFuncion,com.rapidsist.comun.bd.Registro registro )
      throws com.rapidsist.portal.catalogos.LogicaNegocioException, java.rmi.RemoteException;

   /**
    * Realiza la consulta de la historia de los movimientos de un registro.
    * @param registro Objeto registro con los datos de los campos llave de cada tabla.
    * @param sCveFuncion Es la clave de la función.
    * @return Objeto Registro con los datos ordenados listos para presentarse en la jsp.
	* @throws RemoteException Se generó un error al consultar la bitácora.
    * @throws SQLException Se generó un error al consulta la bitácora.
    */
   public java.util.LinkedList consultaBitacora( java.lang.String sCveFuncion,com.rapidsist.comun.bd.Registro registro )
      throws java.sql.SQLException, java.rmi.RemoteException;

}
