/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.bitacora.datos;

/**
 * Home interface for BitacoraSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface BitacoraSLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BitacoraSL";
   public static final String JNDI_NAME="BitacoraSL";

   public com.rapidsist.portal.bitacora.datos.BitacoraSL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
