/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.configuracion;

/**
 * Local home interface for PortalSL.
 * @xdoclet-generated at 22-abril-05 05:33 PM
 */
public interface PortalSLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PortalSLLocal";
   public static final String JNDI_NAME="PortalSLLocal";

   public com.rapidsist.portal.configuracion.PortalSLLocal create()
      throws javax.ejb.CreateException;

}
