/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.catalogos;

/**
 * Home interface for CatalogoSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface CatalogoSLHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CatalogoSL";
   public static final String JNDI_NAME="CatalogoSL";

   public com.rapidsist.portal.catalogos.CatalogoSL create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
