/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.catalogos;

/**
 * Local interface for CatalogoSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface CatalogoSLLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Obtiene un registro de un catálogo en base a la llave primaria.
    * @param registro Llave primaria.
    * @param sCatalogo Nombre del catálogo.
    * @return Objeto Registro resultado de la consulta.
    * @throws LogicaNegocioException Se generó un error al obtener el registro.    
	*/
   public com.rapidsist.comun.bd.Registro getRegistro( java.lang.String sCatalogo,com.rapidsist.comun.bd.Registro registro ) throws com.rapidsist.portal.catalogos.LogicaNegocioException;

   /**
    * Obtiene un registro de un catálogo en base a la llave primaria.
	* @param sCatalogo Nombre del catálogo.
    * @param parametros Parámetros de filtro de búsqueda.
    * @return Objeto Registro resultado de la consulta.
    * @throws LogicaNegocioException Se generó un error al obtener los registros.    
	*/
   public java.util.LinkedList getRegistros( java.lang.String sCatalogo,com.rapidsist.comun.bd.Registro parametros ) throws com.rapidsist.portal.catalogos.LogicaNegocioException;

   /**
    * Genera las operaciones sobre la base de datos a partir de un archivo de configuracion en XML.
    * @param sCatalogo Archivo de configuración para la clase DAO.
    * @param registro Parametros de entrada que provienen de la clase CON.
    * @param iTipoOperacion Tipo de operacion a ejecutar.
    * @return Resultado de la operacion.
    * @throws LogicaNegocioException Se generó un error al generar las operaciones.    
	*/
   public com.rapidsist.portal.catalogos.ResultadoCatalogo operacionCatalogo( java.lang.String sCatalogo,com.rapidsist.comun.bd.Registro registro,int iTipoOperacion ) throws com.rapidsist.portal.catalogos.LogicaNegocioException;

   /**
    * Ejecuta las operaciones de alta, baja y modificación sobre la base de datos. en XML.
    * @param sCatalogo Clave de la función a ejecutar.
    * @param registro Parametros de entrada que provienen de la clase CON.
    * @param iTipoOperacion Tipo de operacion a ejecutar.
    * @return Resultado de la operacion.
    * @throws LogicaNegocioException Se generó un error en la modificación.    
	*/
   public com.rapidsist.portal.catalogos.ResultadoCatalogo modificacion( java.lang.String sCatalogo,com.rapidsist.comun.bd.Registro registro,int iTipoOperacion ) throws com.rapidsist.portal.catalogos.LogicaNegocioException;

}
