/*
 * Generated by XDoclet - Do not edit!
 */
package com.rapidsist.portal.catalogos;

/**
 * Local home interface for CatalogoSL.
 * @xdoclet-generated at 1-junio-05 07:56 PM
 */
public interface CatalogoSLLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CatalogoSLLocal";
   public static final String JNDI_NAME="CatalogoSLLocal";

   public com.rapidsist.portal.catalogos.CatalogoSLLocal create()
      throws javax.ejb.CreateException;

}
