addMenu('Demo', 'm0');
addSubMenu('m0', 'Facial', 'Facial ', '', 'm1', '');
addLink('m1', 'Demaquillantes', 'Demaquillantes ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=1&CveCategoria=1&Filtro=ProductosCategorias&NomFamiliaProducto=Facial&NomCategoria=Demaquillantes&UrlFotoProducto=49&Color=FFDFFF&Encabezado=EL INICIO DEL RITUAL DE BELLEZA&Pie=Un optimo demaquillado prepara la piel para recibir los beneficios de los tratamientos  específicos. Los limpiadores Aspid son formulaciones que se eliminan con agua al cien por ciento, haciendo de lo práctico algo perfecto.', '');
addLink('m1', 'Lociones y tónicos', 'Lociones y tónicos ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=1&CveCategoria=2&Filtro=ProductosCategorias&NomFamiliaProducto=Facial&NomCategoria=Lociones y tónicos&UrlFotoProducto=49&Color=FFDFFF&Encabezado=EQUILIBRIO HIDRATANTE.&Pie=El primer paso de  belleza se complementa con la tonificación adecuada. Los tónicos y lociones Aspid, por sus formulaciones específicas, permiten que la piel retome su propio equilibrio de funcionamiento gracias a la combinación de activos hidratantes y estimulantes.', '');
addLink('m1', 'Cremas de tratamiento', 'Cremas de tratamiento ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=1&CveCategoria=3&Filtro=ProductosCategorias&NomFamiliaProducto=Facial&NomCategoria=Cremas de tratamiento&UrlFotoProducto=49&Color=FFDFFF&Encabezado=DEVUELVE LA LOZANÍA A LA PIEL Y PROPORCIONA VITALIDAD INTENSA.&Pie=Estos productos tienen una riqueza tal que satisface de forma natural la sed de su piel con un verdadero poder humectante.', '');
addLink('m1', 'Cremas nutritivas', 'Cremas nutritivas ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=1&CveCategoria=4&Filtro=ProductosCategorias&NomFamiliaProducto=Facial&NomCategoria=Cremas nutritivas&UrlFotoProducto=49&Color=FFDFFF&Encabezado=PREPARACIÓN NOCTURNA DE LA PIEL.&Pie=La noche es el momento mas propicio para regenerar la piel. Aspid Profesional potencia este proceso con las fórmulas cosmédicas de vanguardia  que logran una óptima renovación celular cutánea.', '');
addLink('m1', 'Mascarillas', 'Mascarillas ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=1&CveCategoria=5&Filtro=ProductosCategorias&NomFamiliaProducto=Facial&NomCategoria=Mascarillas&UrlFotoProducto=49&Color=FFDFFF&Encabezado=15 MINUTOS PARA UNA PIEL RADIANTE.&Pie=Una rápida puesta a punto de la piel se consigue con una limpieza profunda y una mayor penetración de nutrientes, humectantes y reductores de grasa; todo esto con las mascarillas Aspid Profesional.', '');
addLink('m0', 'Aromocosmética', 'Aromocosmética ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=2&CveCategoria=SC&Filtro=Categorias&NomFamiliaProducto=Aromocosmética&NomCategoria=&UrlFotoProducto=208&Color=CCBBEE&Encabezado=&Pie=', '');
addLink('m0', 'Línea corporal', 'Línea corporal ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=3&CveCategoria=SC&Filtro=Categorias&NomFamiliaProducto=Linea corporal&NomCategoria=&UrlFotoProducto=3&Color=C6FFC6&Encabezado=PARA LUCIR ESCULTURAL.&Pie=Un cuerpo de impacto, con tersura y bien protegido son los objetivos de la linea corporal de Aspid Profesional.', '');
addLink('m0', 'Microenergéticos', 'Microenergéticos ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=4&CveCategoria=SC&Filtro=Categorias&NomFamiliaProducto=Microenergéticos&NomCategoria=&UrlFotoProducto=221&Color=9E9EBE&Encabezado=ACTIVOS CONCENTRADOS PARA TODO TIPO DE PIEL.&Pie=Estos productos brindan a la piel el complemento ideal cuando más lo necesita:Cada cambio de estación, para ocasiones especiales o bien si la piel necesita un tratamiento intensivo y requiere un complemento Ultra Nutritivo.', '');
addLink('m0', 'Línea capilar', 'Línea capilar ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=5&CveCategoria=SC&Filtro=Categorias&NomFamiliaProducto=Línea capilar&NomCategoria=&UrlFotoProducto=156&Color=996633&Encabezado=PRODUCTOS PARA EL CUIDADO DEL CABELLO.&Pie=Una cabellera sana toma su belleza desde la raíz, es por eso que Aspid Profesional tiene productos que nutren desde la piel cabelluda hasta las puntas.', '');
addLink('m0', 'Línea solar', 'Línea solar ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=6&CveCategoria=SC&Filtro=Categorias&NomFamiliaProducto=Linea solar&NomCategoria=&UrlFotoProducto=168&Color=FFB56A&Encabezado=&Pie=', '');
addSubMenu('m0', 'Color', 'Color ', '', 'm2', '');
addLink('m2', 'Maquillaje fluido', 'Maquillaje fluido ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=1&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Maquillaje fluido&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Maquilift', 'Maquilift long wearing ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=2&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Maquilift long wearing&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Full mask', 'Full mask ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=3&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Full mask&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Lapiz labial', 'Lapiz labial ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=4&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Lapiz labial&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Rubor compacto', 'Rubor compacto ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=5&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Rubor compacto&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Sombras compactas', 'Sombras compactas ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=6&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Sombras compactas&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Camouflage color', 'Camouflage color ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=7&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Camouflage color&UrlFotoProducto=246&Color=FF9900&Encabezado=&Pie=', '');
addLink('m2', 'Polvo compacto', 'Polvo compacto ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CR&CveProducto=J278&CveFamiliaProducto=8&Encabezado=&Detalle=NO&NomFamiliaProducto=Color&CveCategoria=8&Pie=&NomCategoria=Polvo compacto&UrlFotoProducto=J278-249&CveColor=FF9900&Ventana=Si&Encabezado=&Pie=', '');
//addLink('m2', 'Polvo compacto', 'Polvo compacto ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=8&CveCategoria=8&Filtro=ProductosCategorias&NomFamiliaProducto=Color&NomCategoria=Polvo compacto&UrlFotoProducto=49&Color=FF9900&Encabezado=&Pie=', '');
// addLink('m0', 'Fitocompuestos', 'Fitocompuestos ', '/portal/ProcesaCatalogo?Funcion=AspidPortalProductos&OperacionCatalogo=CT&CveFamiliaProducto=9&CveCategoria=SC&Filtro=Categorias&NomFamiliaProducto=Fitocompuestos&NomCategoria=&UrlFotoProducto=239&Color=6CDB6C&Encabezado=&Pie=', '');
endMenu();








